// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPJWK5KSe3x__m72loXRdkE-xrHBaPEAo',
    appId: '1:653486530463:web:0fe450444bc37f196267aa',
    messagingSenderId: '653486530463',
    projectId: 'thehinneh-notes',
    authDomain: 'thehinneh-notes.firebaseapp.com',
    storageBucket: 'thehinneh-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_pii0NTwnU_ZZ0uwZi1lrEqf3-3pJtQE',
    appId: '1:653486530463:android:ec7763c67102ebea6267aa',
    messagingSenderId: '653486530463',
    projectId: 'thehinneh-notes',
    storageBucket: 'thehinneh-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjpoQ28QWgwp51jJlezIP-09sj6EcvarM',
    appId: '1:653486530463:ios:786c95def50849536267aa',
    messagingSenderId: '653486530463',
    projectId: 'thehinneh-notes',
    storageBucket: 'thehinneh-notes.appspot.com',
    iosClientId: '653486530463-b2pbk7kpev50sl47skvd8b0cg1l5aeop.apps.googleusercontent.com',
    iosBundleId: 'com.thehinneh.personalnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjpoQ28QWgwp51jJlezIP-09sj6EcvarM',
    appId: '1:653486530463:ios:786c95def50849536267aa',
    messagingSenderId: '653486530463',
    projectId: 'thehinneh-notes',
    storageBucket: 'thehinneh-notes.appspot.com',
    iosClientId: '653486530463-b2pbk7kpev50sl47skvd8b0cg1l5aeop.apps.googleusercontent.com',
    iosBundleId: 'com.thehinneh.personalnotes',
  );
}
